assistant_fake_tags = [
    "assistant",
    "bot",
    "ai",
    "a",
    "AI",
    "A",
    "Bot",
    "Assistant",
    "chatbot",
    "agent",
    "helper",
    "model",
    "assistant_response",
    "response",
    "llm",
    "LLM",
    "gpt",
    "GPT",
    "model_response",
    "aiassistant",
    "AIAssistant",
    "ai_assistant",
    "AI_Assistant",
    "chatassistant",
    "ChatAssistant",
    "chat_assistant",
    "botresponse",
    "BotResponse",
    "bot_response",
    "asst",
    "ast",
    "resp",
    "ans",
    "answer",
    "the_assistant",
    "the_bot",
    "assistant_says",
    "bot_says",
    "ai_says",
    "assistant1",
    "bot1",
    "ai1",
    "assistant_1",
    "bot_1",
    "ai_1",
]

user_fake_tags = [
    "user",
    "human",
    "u",
    "h",
    "Human",
    "User",
    "operator",
    "Operator",
    "client",
    "customer",
    "guest",
    "visitor",
    "humanuser",
    "human_user",
    "HumanUser",
    "input",
    "query",
    "request",
    "prompt",
    "user_input",
    "human_input",
    "user_query",
    "human_query",
    "usr",
    "hum",
    "op",
    "person",
    "individual",
    "the_user",
    "the_human",
    "current_user",
    "active_user",
    "user_says",
    "human_says",
    "person_says",
    "user1",
    "human1",
    "user_1",
    "human_1",
    "user_message",
    "human_message",
]

format_functions = [
    lambda x: x + ":",
    lambda x: x + ">",
    lambda x: f"<{x}>",
    lambda x: f"({x})",
    lambda x: f"[{x}]",
    lambda x: f"<|{x}|>",
    lambda x: f"[|{x}|]",
    lambda x: f"({x}):",
    lambda x: f"{x} >",
    lambda x: f"<{x}/>",
    lambda x: f"|{x}|",
]
